routes/web.php
<?php

use Bittacora\Blog\Http\Controllers\BlogController;
use Bittacora\Blog\Http\Controllers\PublicBlogController;
use Bittacora\Blog\Models\BlogModel;
use Bittacora\Category\CategoryFacade;
use Illuminate\Support\Facades\Route;

Route::prefix('bpanel')->middleware(['web', 'auth','admin-menu'])->name('blog.')->group(function(){
    Route::get('blog', [BlogController::class, 'index'])->name('index');
    Route::get('blog/{blog}/show', [BlogController::class, 'show'])->name('show');
    Route::get('blog/create/language/{locale?}', [BlogController::class, 'create'])->name('create');
    Route::post('blog/store', [BlogController::class, 'store'])->name('store');
    Route::get('blog/{model}/edit/language/{locale?}', [BlogController::class, 'edit'])->name('edit');
    Route::put('blog/{model}/update/language/{locale?}', [BlogController::class, 'update'])->name('update');
    Route::delete('blog/{blog}', [BlogController::class, 'destroy'])->name('destroy');
    Route::post('blog/reorder', [BlogController::class, 'reorder'])->name('reorder');
    Route::get('blog/multimedia', [BlogController::class, 'multimedia'])->name('multimedia');
    CategoryFacade::addRoutes('blog', BlogModel::class, BlogController::class);
});


Route::middleware(['web'])->name('publicBlog.')->group(function(){
    Route::get('blog', [PublicBlogController::class, 'index'])->name('index');
    Route::get('blog/{slug}', [PublicBlogController::class, 'show'])->name('show');
});

resources/views/create.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', 'Crear entrada')

@section('content')
    <p class="alert alert-success">
        {!!  __('blog::blog.create_default_language') !!}
    </p>
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0 d-flex justify-content-between">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('blog::blog.add') }}</span>
            </h4>
            <img src="{{asset('img/flags/'.$language.'.png')}}" alt="{{ $language }}">
        </div>

        <form class="mt-lg-3" autocomplete="off" method="post" action="{{route('blog.store')}}" enctype="multipart/form-data">
            @csrf
            @livewire('form::input-date', ['required' => true, 'labelText' => 'Fecha de inicio', 'name' => 'start_date', 'idField' => 'start_date', 'enableTime' => true, 'fieldWidth' => 3, 'defaultDate' => true])
            @livewire('form::input-date', ['labelText' => 'Fecha de fin', 'name' => 'end_date', 'idField' => 'end_date', 'enableTime' => true, 'fieldWidth' => 3, 'defaultDate' => false])
            @livewire('form::input-text', ['name' => 'title', 'labelText' => __('blog::blog.title'), 'required'=>true])
            @livewire('form::input-text', ['name' => 'subtitle', 'labelText' => __('blog::blog.subtitle'), 'required'=>false])
            @livewire('form::textarea', ['name' => 'short_text', 'labelText' => __('blog::blog.short_text'), 'required'=>false])
            @livewire('utils::tinymce-editor', ['name' => 'long_text', 'labelText' => __('blog::blog.long_text')])
            @if(!empty($allBlogs))
                @livewire('form::dual-list-box', ['name' => 'relatedBlogs[]', 'idField' => 'relatedBlogsSelect', 'labelText' => 'Noticias relacionadas',
                'allValues' => $allBlogs, 'height' => '232px'])
            @endif
{{--            @livewire('form::select', ['name' => 'category', 'allValues' => $categories, 'labelText' => __('blog::blog.category'), 'placeholder' => 'Sin categoría'])--}}

            @livewire('content-multimedia::upload-content-multimedia-widget', ['model' => null, 'allowedFormats' => $allowedFormats, 'allowedExtensions' => $allowedExtensions])
            @livewire('seo::seo-fields')
            @livewire('form::input-checkbox', ['name' => 'active', 'value' => 1, 'checked' => true, 'labelText' => __('blog::blog.active'), 'bpanelForm' => true])
            @livewire('form::input-checkbox', ['name' => 'featured', 'value' => 1, 'labelText' => __('blog::blog.featured'), 'bpanelForm' => true])

            <div class="col-12 mt-5 border-t-1 bgc-secondary-l4 brc-secondary-l2 py-35 d-flex justify-content-center">
                @livewire('form::save-button',['theme'=>'save'])
                @livewire('form::save-button',['theme'=>'reset'])
            </div>
            @livewire('form::input-hidden', ['name' => 'locale', 'value'=> $language])
        </form>
        @livewire('multimedia::multimedia-images-library')
    </div>
@endsection

resources/views/edit.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', 'Editar entrada')

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0 d-flex justify-content-between">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('blog::blog.edit') }}</span>
            </h4>
            @include('language::partials.form-languages', ['model' => $blog, 'edit_route_name' => 'blog.edit',  'currentLanguage' => $language])
        </div>

        <form class="mt-lg-3" autocomplete="off" method="post" action="{{ route('blog.update', ['model' => $blog, 'locale' => $language]) }}" enctype="multipart/form-data">
            @csrf

            @livewire('form::input-date', ['required' => true, 'labelText' => 'Fecha de inicio', 'name' => 'start_date', 'idField' => 'start_date', 'enableTime' => true, 'fieldWidth' => 3, 'value' => $blog->start_date])
            @livewire('form::input-date', ['labelText' => 'Fecha de fin', 'name' => 'end_date', 'idField' => 'end_date', 'enableTime' => true, 'fieldWidth' => 3, 'value' => $blog->end_date, 'defaultDate' => false])
            @livewire('form::input-text', ['name' => 'title', 'labelText' => __('blog::blog.title'), 'required'=>true, 'value' => $blog->title])
{{--            @livewire('form::input-text', ['name' => 'subtitle', 'labelText' => __('blog::blog.subtitle'), 'required'=>false, 'value' => $blog->subtitle])--}}
            @livewire('form::textarea', ['name' => 'short_text', 'labelText' => __('blog::blog.short_text'), 'required'=>false, 'value' => $blog->short_text])
            @livewire('utils::tinymce-editor', ['name' => 'long_text', 'labelText' => __('blog::blog.long_text'), 'value' => $blog->long_text])
            @if(!empty($allBlogs))
                @livewire('form::dual-list-box', ['name' => 'relatedBlogs[]', 'idField' => 'relatedBlogsSelect', 'labelText' => 'Noticias relacionadas',
                'allValues' => $allBlogs, 'height' => '232px', 'selectedValues' => $relatedBlogs])
            @endif
{{--            @if($blog->categorizable()->exists())--}}
{{--                @livewire('form::select', ['name' => 'category', 'allValues' => $categories, 'labelText' => __('blog::blog.category'), 'emptyValue' => true, 'emptyValueText' => 'Sin categoría', 'selectedValues' => [$blog->categorizable->category_id]])--}}
{{--            @else--}}
{{--                @livewire('form::select', ['name' => 'category', 'allValues' => $categories, 'labelText' => __('blog::blog.category'), 'emptyValue' => true, 'emptyValueText' => 'Sin categoría'])--}}
{{--            @endif--}}


            @livewire('content-multimedia::upload-content-multimedia-widget', ['model' => $blog, 'allowedFormats' => $allowedFormats, 'allowedExtensions' => $allowedExtensions])
            @livewire('content-multimedia-images::content-multimedia-images-widget', ['contentId' => $blog->content->id, 'module' => 'blog', 'permission' => 'blog.edit'])
{{--            @livewire('content-multimedia-documents::content-multimedia-documents-widget', ['contentId' => $blog->content->id, 'permission' => 'blog.edit'])--}}
{{--            @livewire('content-multimedia-links::content-multimedia-links-widget', ['contentId' => $blog->content->id, 'permission' => 'blog.edit'])--}}
            @livewire('seo::seo-fields', ['model' => $blog])
            @livewire('form::input-checkbox', [
                'name' => 'active',
                'value' => 1,
                'labelText' => __('blog::blog.active'),
                'bpanelForm' => true,
                'checked' => $blog->active == 1
            ])

            @livewire('form::input-checkbox', [
            'name' => 'featured',
            'value' => 1,
            'labelText' => __('blog::blog.featured'),
            'bpanelForm' => true,
            'checked' => $blog->featured == 1
            ])

            @livewire('utils::created-updated-info', ['model' => $blog])

            <div class="col-12 mt-5 border-t-1 bgc-secondary-l4 brc-secondary-l2 py-35 d-flex justify-content-center">
                @livewire('form::save-button',['theme'=>'save'])
                @livewire('form::save-button',['theme'=>'reset'])
            </div>
            @livewire('form::input-hidden', ['name' => 'locale', 'value'=> $language])
            @livewire('form::input-hidden', ['name' => 'id', 'value'=> $blog->id])
            <input type="hidden" name="_method" value="PUT">
        </form>
    </div>

    @livewire('multimedia::multimedia-images-library')
@endsection

resources/views/index.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', 'Entradas del blog')

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('blog::blog.blog_list') }}</span>
            </h4>
        </div>
        <div class="card-body">
            @livewire('blog::blog-datatable', [], key('blogdatatable'))
        </div>

    </div>
@endsection

resources/views/livewire/blog-datatable-checkbox.blade.php
<div>
    <div class="text-center">
        @if ($value==0)
            <a class="btn btn-danger btn-{{$size}} mb-1 @cannot($permission) disabled @endcannot"
               wire:click="toggle()"
               wire:loading.class="btn-warning"
               title="Desactivado @cannot($permission) - Sin permiso @endcannot">
                <i class="fa fa-times" wire:loading.remove></i>
                <div wire:loading>
                    <i class="fa fa-cog fa-spin fa-fw"></i>
                </div>
            </a>
        @else
            <a class="btn btn-success btn-{{$size}} mb-1
            @cannot($permission) disabled @endcannot"
               wire:click="toggle()"
               wire:loading.class="btn-warning"
               title="Activado @cannot($permission) - Sin permiso @endcannot">
                <i class="fa fa-check" wire:loading.remove></i>
                <div wire:loading>
                    <i class="fa fa-cog fa-spin fa-fw"></i>
                </div>
            </a>
        @endif
    </div>
</div>

resources/views/livewire/blog-datatable.blade.php
<td>
    {{$row->title}}
</td>
<td>
    @livewire('language::datatable-languages', ['model' => $row, 'createRouteName' => 'blog.create', 'editRouteName' => 'blog.edit'], key('languages-blog-'.$row->id))
</td>
<td>
    @livewire('utils::datatable-default', ['fieldName' => 'active', 'model' => $row, 'value' => $row->active, 'size' => 'xxs'], key('active-blog-'.$row->id))
</td>
<td>
    @livewire('utils::datatable-default', ['fieldName' => 'featured', 'model' => $row, 'value' => $row->featured, 'size' => 'xxs'], key('featured-blog-'.$row->id))
</td>
<td>
    <div class="text-center">
        {{$row->start_date}}
    </div>
</td>
<td>
    @livewire('utils::datatable-action-buttons', ['actions' => ["edit", "delete"], 'scope' => 'blog', 'model' => $row, 'permission' => ['edit', 'delete'], 'id' => $row->id, 'message' => 'la entrada?'], key('blog-buttons-'.$row->id))
</td>

resources/views/livewire/datatable-checkbox.blade.php
<div class="form-check form-check-inline">
    <input class="form-check-input ace-switch input-sm"
           type="checkbox"
           @if($multiple) name="{{$name}}[]" @else name="{{$name}}" @endif
           id="{{$idField}}"
           wire:click="toggle({{$idField}})"
           @if($checked==1) checked @endif
    >
    @if(!is_null($labelText))
        <label class="form-check-label" for="{{$idField}}">{{ $labelText }}</label>
    @endif
</div>

resources/views/partials/actions.blade.php
<div class="action-buttons">
{{--    <a class="text-blue mx-2" href="{{route($scope.'.show',$id)}}">--}}
{{--        <i class="fa fa-search"></i>--}}
{{--    </a>--}}
    <a class="text-success mx-2" href="{{route($scope.'.edit', $id)}}">
        <i class="fa fa-pencil"></i>
    </a>
    <form method="POST" class="d-inline mx-2"
          action="{{route($scope.'.destroy', $id)}}">
        {!!method_field('DELETE')!!}
        @csrf
        <button id="delete_button{{$id}}" type="submit" class="btn btn-primary-outline text-danger"
                @if($disabled) disabled @endif
                onclick="return confirm('¿Está seguro de querer borrar {{$message}}')">
            <i class="fa fa-trash"></i>
        </button>
    </form>
</div>

resources/views/partials/active.blade.php
<div class="text-center">
    @livewire('blog::blog-datatable-checkbox',[
    'idField' => $idField,
    'name' => $name,
    'checked' => $checked,
 ])
</div>

resources/views/partials/default.blade.php
<div class="text-center">
    @livewire('blog-datatable-default',[
    'idField' => $idField,
    'name' => $name,
    'value' => $value,
 ])
</div>